version: "3.9"
services:
  api:
    build: .
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - .:/code
    working_dir: /code
    depends_on:
      - db
      - redis
  worker:
    build: .
    command: celery -A app.tasks.queue worker --loglevel=info
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - APP_SECRET=${APP_SECRET}
      - CELERY_EAGER=false
    volumes:
      - .:/code
    working_dir: /code
    depends_on:
      - db
      - redis
  scheduler:
    build: .
    command: celery -A app.tasks.queue beat --loglevel=info
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - APP_SECRET=${APP_SECRET}
      - CELERY_EAGER=false
    volumes:
      - .:/code
    working_dir: /code
    depends_on:
      - redis
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autojob
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
volumes:
  pgdata:
